stages:
  - build

build:
  stage: build
  image: gradle:5.4.0-jre11-slim
  script:
    - java -version
    - gradle --console=plain test jar shadowJar
    # show jar size in log
    - du -sbh build/libs/*.jar
    # verify that launch script and fat jar is working
    - chmod +x optic-lua
    - ./optic-lua --version
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      # only applies if benchmarks are run
      - build/reports/jmh
      - build/reports/tests
      # jars
      - build/libs/
