stages:
  - build

build:
  stage: build
  image: gradle:jdk10-slim
  script:
    - java -version
    # - chmod +x gradlew
    - gradle build jmh
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/reports/jmh
      - build/reports/tests
