stages:
  - build

build:
  stage: build
  image: gradle:5.4.0-jre11-slim
  script:
    - java -version
    - gradle --console=plain test jacocoTestReport jar shadowJar runtimeJar
    # show jar size in log
    - du -sbh build/libs/*.jar
    # verify that launch script and fat jar is working
    - java -jar build/libs/optic-lua.jar --version
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      # tests, coverage, benchmarks, etc.
      - build/reports/
      # jars
      # - build/libs/
